Speedy try at letting command/cb functions be async/awaitable
tiangolo/typer pull request #128
Opened 2020-06-26 02:48 UTC by jessekrubin

Seems to work.
Modified one of your (@tiangolo) test files.

The only thing that is funky is the click 2-3 param warning I get when doing something with context.

2020-09-09 07:27 UTC, thedrow requested changes
Please refrain from including code formatting in this PR.
It's very hard to review the changes this way.

2020-09-16 22:21 UTC, jessekrubin commented
> Please refrain from including code formatting in this PR.
> 
> It's very hard to review the changes this way.

@thedrow I used the script for formatting. I think my wsl git changed the file permissions which makes git think the whole of a file(s) was/were changed

2022-03-24 11:51 UTC, hozn commented
Is this still on the slate for inclusion or is this OBE?

2024-03-08 15:11 UTC, svlandeg commented
Closing this PR in favour of https://github.com/tiangolo/typer/pull/213 which contains a more clean version of the diff. Thanks for your contribution @jessekrubin and apologies for taking so long to engage with this! We'll continue the review over at #213.

2024-03-08 15:12 UTC, closed without merging

2024-03-21 16:19 UTC, jessekrubin commented
@svlandeg no prob. The formatting got all screwy (I think bc I was on a wonky computer).